mattermost/mattermost-test-management

.github/PULL_REQUEST_TEMPLATE.md

This PR adds template for pull requests.
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/6"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore(docs): add template for pull requests

---

README.md

Cleaned up some grammar and spelling mistakes in the readme, as well as added some text about specific deno tasks like `deno task silverbullet` and `deno task start`. 
N/A, just readme text changes.
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/31"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: edit readme + add info about deno tasks

---

www/routes/test-cases/[...slug].tsx

This fixes the issue https://github.com/mattermost/mattermost-test-management/issues/32 as reported by @simcard0000.
In Gitpod and Deno Deploy, the markdown file requires case-sensitive when accessing the file. Not really sure why it's has different behavior in local.
Can be verified by accessing the web application as deployed in Gitpod (ex. `https://8000-mattermost-mattermostte-5z2tnd7c7j3.ws-us78.gitpod.io/test-cases/apps-framework/figma/mm-t5157`) which should not show 500 error.
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/34"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: broken test page

---

README.md

Added a point about getting Elasticsearch up and running through the `docker compose up` command.
N/A, just readme text changes.
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/37"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

docs: add info about elasticsearch in readme

---

data/test-cases/suite/system-console/MM-Tnnn.md

Should match title and custom description in root html.
- automated test at https://github.com/mattermost/mattermost-webapp/pull/12062
Could spin up at https://github.com/mattermost/mattermost-webapp/pull/12062
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/58"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-43924): Should match title and custom description in root html

---

data/test-cases/mobile-v2/invite-people/MM-T5361.md

This fills in the previously missing test steps for the placeholder [MM-T5361](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T5361) regarding https://github.com/mattermost/mattermost-mobile/pull/6877
Specifically for this test we need to ensure that no results will appear in the search list under certain conditions.
Feature Ticket ➜ [MM-42835](https://mattermost.atlassian.net/browse/MM-42835)
[Figma design](https://www.figma.com/file/mvJXgiirM4ucPW8bHAvM4G/MM-39720-Invite-People?node-id=276%3A230414)
[Figma prototype](https://www.figma.com/proto/mvJXgiirM4ucPW8bHAvM4G/MM-39720-Invite-People?page-id=117%3A212251&node-id=206%3A218607&viewport=478%2C48%2C0.15&scaling=min-zoom&st …

test(MM-T5361): Mobile V2: Invite - Should show no results item in search list

---

data/test-cases/cloud/signup-trial-and-upgrade/MM-T4892.md
data/test-cases/mobile-v2/invite-people/MM-T5362.md

This is a minor update to the existing test case [MM-T4892](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4892)
As of the Cloud release on February 2, 2023 new customers will no longer be able to select monthly as a billing option. As such they will not be able to downgrade manually and will instead need to contact support to facilitate downgrading. Grandfathered monthly billed customers will retain the ability to downgrade so for now this test can remain in place as we can, and still need to test it.
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/65"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T4892): Self-Serve: Downgrade from Professional plan

---

data/test-cases/calls/MM-Tnnn1.md
data/test-cases/calls/MM-Tnnn2.md

- Added test for global widget (based from https://github.com/mattermost/mattermost-plugin-calls/blob/main/e2e/tests/global_widget.spec.ts)
- Added test for joining a call (based from https://github.com/mattermost/mattermost-plugin-calls/blob/main/e2e/tests/join_call.spec.ts, added one for RHS post)
Test cases automated at https://github.com/mattermost/mattermost-webapp/pull/12300
In any test server

test(widget and join): Global widget and joining a call

---

data/test-cases/channels/messaging/cancel-message-editing.md

Should discard edits made to messages after cancelling

test: discard message edits after cancelling

---

data/test-cases/suite/work-templates/work_templates_unavailable_when_playbooks_restricted.md

Similar to https://github.com/mattermost/mattermost-test-management/pull/100 but designed to address changes to Playbook permissions
Jira ticket: [Account for user permissions in template flow entry points](https://mattermost.atlassian.net/browse/MM-51843)

test(MM-51843): Work Templates menu unavailable when ability to create Public Playbooks is disabled

---

data/test-cases/channels/gif-picker/insert-key1.md
data/test-cases/channels/gif-picker/insert-key2.md
src/util/test_case.ts

Add manual test steps for Gif picker
n/a

test(MM-54404): Add e2e tests for gif picker

---

data/test-cases/plugins/gitlab/slash-commands-and-setup/code-preview.md

This is the first test added for the GitLab code preview functionality new in v`1.7.0`
**note**: This is the first of several tests. I wanted to make a commit to work though the process.   
Typical format for test cases:
Test coverage for https://github.com/mattermost/mattermost-plugin-gitlab/pull/299

Included first test for GitLab code preview

---

data/test-cases/plugins/confluence/MM-T3982.md
data/test-cases/plugins/zoom/general/MM-T4632.md
data/test-cases/plugins/zoom/general/MM-T4633.md
data/test-cases/plugins/zoom/general/MM-T4965.md
data/test-cases/plugins/zoom/jwt/MM-T4630.md
data/test-cases/plugins/zoom/jwt/MM-T4631.md
data/test-cases/plugins/zoom/oauth-account-level-app/MM-T4628.md
data/test-cases/plugins/zoom/oauth-account-level-app/MM-T4629.md
data/test-cases/plugins/zoom/oauth-account-level-app/MM-T4634.md
data/test-cases/plugins/zoom/oauth-user-managed-app/MM-T4624.md
data/test-cases/plugins/zoom/oauth-user-managed-app/MM-T4625.md
data/test-cases/plugins/zoom/oauth-user-managed-app/MM-T4626.md
data/test-cases/plugins/zoom/oauth-user-managed-app/MM-T4627.md
data/test-cases/plugins/zoom/oauth-user-managed-app/MM-T4635.md

Replaced legacy/broken GitBook links with permalinks [via Marketing](https://docs.google.com/spreadsheets/d/1O601H_A0IM8pR3FOfue29_C8flGV7xK3ts-tJUVDHHg/edit#gid=0).
Addresses: https://mattermost.atlassian.net/browse/MM-55436

Replaced legacy GitBook URLs with PL links

---

data/test-cases/plugins/ms-teams-sync/text-formatting/Formatting_latex.md

Captured from MS Teams plugin v1.4.0 bug bash; #notabug. 
Noting for future reference and for comparison that a post formatted as LaTeX from the Mattermost side is currently known and expected to not render properly on the MS Teams side.

test(feature): Added test for LaTeX currently not expected to render in MS Teams

---

data/test-cases/channels/channels/MM-T847.md

Removed extra info about channel order, which isn't at the core of this test case and depends on config anyway.

Update MM-T847.md to remove unneeded checks for channel order

---

src/util/test_case.ts

Updating teamOptions list to add current teams available in Jira. Did not remove old teams as that could affect existing tests; those should be updated in a targeted way. 
To avoid validation failures such as on https://github.com/mattermost/mattermost-test-management/pull/168
Adding:
```
ABC
Cloud Platform
Customer Reliability Engineering
Deployment Engineering
Integrations
MS Teams
XYZ
```

Update teamOptions list

---

.github/CODEOWNERS

Removed codeowners to all folders to unblock developers except at `.github/workflows` which is assigned to QA core and build engineers. Ref: https://github.com/mattermost/mattermost-test-management/pull/168#issuecomment-2027677122
Note: This PR is awaiting for the separate PR in GH management. Will remove "do not merge" label once merged.

chore: remove codeowner except for .github/workflows

---

data/test-cases/plugins/MM-T2400.md
data/test-cases/plugins/plugin-marketplace/MM-T3452.md

Plugin store is gradually migrated from:
- https://plugins-store.test.mattermost.com to
- https://plugins.releases.mattermost.com
We reflect that change here
Note: Currently both CDN's are working as expected, to facilitate the mgiration. Upon succesfull migration, https://plugins-store.test.mattermost.com will be decomissioned

[chore] migration of plugin-store

---

data/test-cases/plugins/attachment-remover/MM-T5618.md
data/test-cases/plugins/attachment-remover/MM-T5620.md
data/test-cases/plugins/attachment-remover/MM-T5621.md

- Hide option if no permission nor outside edit time limit
Corresponding PR - https://github.com/mattermost/mattermost-plugin-attachments-remover/pull/3

feat(attachment remover): hide option if no permission nor outside edit time limit

---

data/test-cases/suite/system-console/compliance/data-retention-policy/SetGlobalPolicyForAttachmentInHours.md
data/test-cases/suite/system-console/compliance/data-retention-policy/SetGlobalPolicyForMessagesInHours.md

Add tests for Global Retention policy in hours

Add tests for Global Retention policy in hours
