mattermost/mattermost-test-management

data/TEST_CASE_TEMPLATE.md
data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md

This is initial positive flow for co-term expansion. 
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/7"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(co-term expansion): Admins should be able to purchase additional seats for existing license

---

README.md

- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/9"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: add line brake in readme

---

data/test-cases/cloud/customer-portal/co-term-expansion/MM-T5295.md
data/test-cases/cloud/customer-portal/co-term-expansion/MM-Test-Case-1.md

<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/15"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(Co-Term Expansion): Email confirmation on purchase

---

data/test-cases/mobile-v2/smoke-test/MM-T4886.md

Correcting typo in step 2 of the test case. Changing `@` to `~`
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/14"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T4886): Update step 2 for existing test MM-T4886.md 

---

.github/PULL_REQUEST_TEMPLATE.md

Adding an example for PR title naming when updating existing test case
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/18"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

chore(docs): Update PULL_REQUEST_TEMPLATE.md with example for existing test cases

---

data/test-cases/channels/messaging/MM-T129.md

Updating existing test case for drafts - changing pencil icon location 
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/28"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T129): Updating expected location of pencil icon for drafts

---

data/test-cases/channels/messaging/MM-T131.md

Updating existing test case for drafts - changing pencil icon location
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/30"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T131): Updating expected location of pencil icon for drafts

---

data/test-cases/channels/messaging/MM-T130.md

Updating existing test case for drafts - changing pencil icon location
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/29"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T130): Updating expected location of pencil icon for drafts

---

data/test-cases/mobile-v2/channels/MM-T4728.md
data/test-cases/mobile-v2/channels/MM-T4730.md
data/test-cases/mobile-v2/channels/MM-T4928.md

- Updated expected initial components for MM-T4728, MM-T4730, and MM-T4928
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/36"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Update channels expected initial components

---

data/test-cases/channels/channel-settings/MM-T884.md

MM-T884 -  Updating existing steps and adding new step 3 
Related PRs:
https://github.com/mattermost/mattermost-server/pull/21639
https://github.com/mattermost/mattermost-webapp/pull/11716
Changes can be seen on this server before merge to main https://mattermost-server-pr-21639.test.mattermost.cloud/
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/39"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T884): Updating existing and adding step 3 to the test case

---

data/test-cases/channels/global-drafts/delete.md

Adding a new test case for global drafts, testing delete from global drafts and cancel delete
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/40"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(delete global draft): adding new test case for deleting global drafts

---

data/test-cases/mobile-v2/account/MM-T4991.md

Adding "report a problem"  to step 1. of the test
Automated test needs to be updated
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/41"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T4991): Adding "report a problem"  to first step

---

data/test-cases/mobile-v2/server-login/MM-T4676.md

Updating server error message in step 3.
related ticket: https://mattermost.atlassian.net/browse/MM-45178
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/42"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T4676): Updating server error step 3.

---

data/test-cases/mobile-v2/messaging/MM-T4897.md
data/test-cases/mobile-v2/messaging/MM-T4900.md

- Updated test cases and test data for MM-T4897, MM-T4900
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/45"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Update test data and test cases for markdown latex and list

---

data/test-by-folder.json
data/test-cases/self-hosted/true-up-support/test-1.md
data/test-cases/self-hosted/true-up-support/test-2.md
data/test-cases/self-hosted/true-up-support/test-3.md

feat(true-up): Test cases for true-up: Support for customers with no connectivity
closes: [MM-49440](https://mattermost.atlassian.net/browse/MM-49440)
Epic: [MM-47851](https://mattermost.atlassian.net/browse/MM-47851)
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/50"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat(true-up): Test cases for true-up: Support for customers with no connectivity

---

data/test-cases/channels/global-drafts/MM-T4409.md
data/test-cases/channels/global-drafts/MM-T4410.md
data/test-cases/channels/global-drafts/MM-T4411.md
data/test-cases/channels/global-drafts/MM-T4412.md
data/test-cases/channels/global-drafts/MM-T4413.md
data/test-cases/channels/global-drafts/MM-T4414.md
data/test-cases/channels/global-drafts/MM-T5366.md

- updating test name following folder naming convention
- setting test status to `active`
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/51"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-T5366): Updating test name to follow folder naming convention and setting active status

---

data/test-cases/channels/global-drafts/Global-Drafts-Onboarding-Tourtip
data/test-cases/channels/global-drafts/Global-Drafts-Onboarding-Tourtip.md

Adding new test for Global Drafts onboarding tour tip
Jira ticket: https://mattermost.atlassian.net/browse/MM-49179
- [] Browser
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/55"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(global drafts-onboarding-tour-tip): New test for Global Drafts onboarding

---

data/test-cases/suite/system-console/site-configuration/customization/MM-Test-Case-1.md

Ref: https://github.com/mattermost/mattermost-webapp/pull/12026
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/68"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added help resources test case

---

data/test-cases/channels/add-user-from-popover/MM-Test-Case-1.md
data/test-cases/channels/team-settings/MM-Test-Case-1.md
data/test-cases/cloud/starter-plan/MM-Test-Case-1.md

Ref:
https://github.com/mattermost/mattermost-webapp/pull/12052
https://github.com/mattermost/mattermost-webapp/pull/12094
https://github.com/mattermost/mattermost-webapp/pull/11553
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/70"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Added Test cases

---

data/test-cases/channels/channel-menu/MM-XXX.md

Adds test cases for channel move to menu options under
https://mattermost.atlassian.net/browse/MM-48845
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/53"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(MM-48845) : Test cases for channel moveTo category sub menu options

---

deno.jsonc
src/deps.ts
src/util/jira.ts
src/util/zephyr.ts

Updated dependencies and pinned exact package versions

chore(dependencies): update dependencies and pin exact package versions

---

data/test-cases/smoke-tests/rolling-upgrades/MM-Taaaa.md

This is a general test case for server upgrades from last stable to release version.
<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/69"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

test(rolling upgrades): Server upgrades from last stable to release version

---

src/deps.ts
www/import_map.json
www/routes/gfm.css.ts
www/routes/test-cases/[...slug].tsx
www/utils/deps.ts
www/utils/markdown.ts

- updated dependencies using 0.178.0 std library
- removed unneeded dependencies
- continued upgrade to `/www` folder which had previous error

chore: update dependencies

---

data/test-cases/channels/archived-channels/MM-T1703.md

- `More Channels` changed to `Browse Channels`
- Removed outdated references to experimental sidebar setting

test(MM-T1703): Update steps with new UI including More Channels to Browse Channels

---

data/test-cases/channels/archived-channels/MM-T1697.md

- `More Channels` changed to `Browse Channels`
- Removed outdated reference to experimental sidebar setting

test(MM-T1697): Update steps with new UI including `More Channels` to `Browse Channels`

---

data/test-cases/suite/sign-in-authentication/MM-Test-Case-1.md

Ref: [MM-50430](Ref: https://mattermost.atlassian.net/browse/MM-50430)

 Added Verify Forgot Password link test cases

---

src/util/jira.ts

- in `.env` file Add a new variable `EMAIL=your.email@example.com`

feat: add email to Auth header when fetching components

---

data/environments.json
data/test-by-folder.json
data/test-cases-manifest.json
data/test-cases/channels/global-drafts/MM-TXX.md

test(bug) : Drafts badge doesn't clear when parent message deleted and removed

---

data/test-cases/integrations/bot-accounts/MM-T1817.md

Follow test update for https://github.com/mattermost/mattermost/pull/24553
@lindy65 I may have missed others to update related to above PR. Please help check and submit change as needed. Thanks!

fix(MM-T1817): update ephemeral post when adding a bot not member of a team

---

data/test-cases/smoke-tests/webapp/MM-T3052.md
data/test-cases/smoke-tests/webapp/MM-T3087.md

Tested smoke tests T3052 T3087 for PR https://github.com/mattermost/mattermost/pull/24793

tested 2 smoketests T3052 T3087

---

data/test-cases/channels/custom-emoji/MM-T2184.md

Tested Custom Emoji in Channel for the PR
[MM-PR-24785](https://github.com/mattermost/mattermost/pull/24785)
Test Server

Tested Custom Emoji T2184

---

data/test-cases/suite/ad-ldap/sysadmin-ui-shows-ldap-users-do-not-deactivate.md

https://github.com/mattermost/mattermost/pull/25167

Show that LDAP users cannot be deactivated

---

data/test-cases/channels/custom-emoji/MM-T2184.md
data/test-cases/suite/system-console/any-page/MM-T955.md

Tested Remove button in System console for the PR [MM-PR-24912](https://github.com/mattermost/mattermost/pull/24912#issuecomment-1773714773)

Tested Remove button in System console T955

---

data/test-cases/channels/files-and-attachments/MM-T2264.md

```
test(MM-T2264): add step 7
```
- https://github.com/mattermost/mattermost/pull/25784
Unable to create test server.
[test-result.txt](https://github.com/mattermost/mattermost-test-management/files/13823655/test-result.txt)

[MM-11777] Add test description for WEBP upload test

---

data/test-by-folder.json
data/test-cases/suite/system-console/user-management/new-ui/test-1.1-view.md
data/test-cases/suite/system-console/user-management/new-ui/test-1.2-search.md
data/test-cases/suite/system-console/user-management/new-ui/test-1.3-export.md
data/test-cases/suite/system-console/user-management/new-ui/test-1.3-sorting.md
data/test-cases/suite/system-console/user-management/new-ui/test-1.4-mysql.md
data/test-cases/suite/system-console/user-management/new-ui/test-1.5-date-range.md

Jira: https://mattermost.atlassian.net/browse/MM-56151
Dev PR: https://github.com/mattermost/mattermost/pull/26055

User Management Test cases

---

data/key-and-path.json
data/test-by-folder.json
data/test-cases-manifest.json
data/test-cases-slugs.json
data/test-cases-toc.json
data/test-cases/channels/permalink-preview/MM-T5526.md
data/test-cases/channels/permalink-preview/test-case-1.md

adding a test for defect : https://mattermost.atlassian.net/browse/MM-56575

Add test case for non channel admin accessing post links

---

data/folder-by-parent.json
data/folders.json
data/key-and-path.json
data/test-by-folder.json
data/test-cases-folders.json
data/test-cases-manifest.json
data/test-cases-slugs.json
data/test-cases-toc.json
data/test-cases/channels/multi-team-and-dms/MM-T459.md
data/test-cases/plugins/MM-T2400.md
data/test-cases/plugins/plugin-marketplace/MM-T3452.md
data/test-cases/suite/notifications/MM-T510.md
data/test-cases/zephyr-reflect-ai-testing/MM-T5594.md

chore(data): sync

---

data/test-cases/plugins/attachment-remover/MM-T5618.md
data/test-cases/plugins/attachment-remover/MM-T5620.md
data/test-cases/plugins/attachment-remover/MM-T5621.md

chore: data sync

---

data/folder-by-parent.json
data/folders.json
data/key-and-path.json
data/test-by-folder.json
data/test-cases-folders.json
data/test-cases-manifest.json
data/test-cases-slugs.json
data/test-cases-toc.json
data/test-cases/desktop-app--native-specific-/landing-page/MM-T5640.md

Playwright Test : https://github.com/mattermost/mattermost/pull/28839

Feat: Make desktop app landing page optional
